test

diff --git a/.github/workflows/dev-pr-label.yml b/.github/workflows/dev-pr-label.yml
--- a/.github/workflows/dev-pr-label.yml
+++ b/.github/workflows/dev-pr-label.yml
@@ -21,3 +21,18 @@ jobs:
           mode: exactly
           count: 1
           labels: "bug, documentation, enhancement, task"
+      - name: Check Milestone
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Get the PR information
+          PR_DATA=$(gh pr view ${{ github.event.pull_request.number }} --json milestone --jq '.milestone')
+
+          # If the milestone is null, fail the workflow
+          if [ "$PR_DATA" == "null" ]; then
+            echo "❌ The pull request does not have a milestone assigned."
+            exit 1
+          fi
+
+          # Output the milestone if it exists
+          echo "✅ The pull request has a milestone assigned: $PR_DATA."
